# Root module generated by the OpenFrame CLI (do not edit by hand — the CLI
# owns this workspace). Provisions a self-contained EKS cluster: dedicated VPC
# (2 AZs, single NAT) + EKS with one managed node group. All inputs come from
# terraform.tfvars.json next to this file.

terraform {
  required_version = ">= 1.15.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 6.52"
    }
  }
}

variable "cluster_name" { type = string }
variable "region" { type = string }

variable "profile" {
  type    = string
  default = ""
}

# Kubernetes <major>.<minor> (e.g. "1.33"); empty means the EKS default.
variable "kubernetes_version" {
  type    = string
  default = ""
}

variable "instance_type" {
  type    = string
  default = "m6i.large"
}

variable "min_nodes" {
  type    = number
  default = 1
}

variable "max_nodes" {
  type    = number
  default = 4
}

variable "desired_nodes" {
  type    = number
  default = 3
}

variable "spot" {
  type    = bool
  default = false
}

provider "aws" {
  region  = var.region
  profile = var.profile != "" ? var.profile : null

  default_tags {
    tags = {
      "openframe:cluster"   = var.cluster_name
      "openframe:managedBy" = "openframe-cli"
    }
  }
}

data "aws_availability_zones" "available" {
  state = "available"
}

locals {
  azs = slice(data.aws_availability_zones.available.names, 0, 2)
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 6.0"

  name = "${var.cluster_name}-vpc"
  cidr = "10.0.0.0/16"

  azs             = local.azs
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]

  enable_nat_gateway = true
  single_nat_gateway = true

  public_subnet_tags = {
    "kubernetes.io/role/elb" = "1"
  }
  private_subnet_tags = {
    "kubernetes.io/role/internal-elb" = "1"
  }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 21.0"

  name               = var.cluster_name
  kubernetes_version = var.kubernetes_version != "" ? var.kubernetes_version : null

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  # The CLI reaches the API server from the operator's machine.
  endpoint_public_access = true

  # The identity running terraform must be able to use the cluster afterwards
  # (kubeconfig auth goes through `aws eks get-token` with the same identity).
  enable_cluster_creator_admin_permissions = true

  eks_managed_node_groups = {
    default = {
      instance_types = [var.instance_type]
      min_size       = var.min_nodes
      max_size       = var.max_nodes
      desired_size   = var.desired_nodes
      capacity_type  = var.spot ? "SPOT" : "ON_DEMAND"
    }
  }
}

output "cluster_name" {
  value = module.eks.cluster_name
}

output "cluster_endpoint" {
  value = module.eks.cluster_endpoint
}

output "cluster_certificate_authority_data" {
  value = module.eks.cluster_certificate_authority_data
}

output "region" {
  value = var.region
}
