# Root module generated by the OpenFrame CLI (do not edit by hand — the CLI
# owns this workspace). Provisions a self-contained EKS cluster: dedicated VPC
# (2 AZs, single NAT) + EKS with one managed node group, the core addons
# (vpc-cni, kube-proxy, coredns) and the EBS CSI driver addon. All inputs come
# from terraform.tfvars.json next to this file.
#
# Module versions are EXACT pins, not ranges. A floating "~> 21.0" once
# resolved to a new minor whose changed defaults broke cluster creation in
# three independent ways (no bootstrapped addons, IMDS hop limit 1, gated
# kubernetes_version data source). Bump the pins deliberately, re-running the
# full create/delete pass afterwards.

terraform {
  required_version = ">= 1.15.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 6.52, < 7.0"
    }
  }
}

variable "cluster_name" { type = string }
variable "region" { type = string }

variable "profile" {
  type    = string
  default = ""
}

# Kubernetes <major>.<minor>. The default is a concrete version, not null:
# EKS module v21 gates a data source on `kubernetes_version == null`, which
# fails at plan time ("Invalid count argument") — the version must be known
# before apply.
variable "kubernetes_version" {
  type    = string
  default = "1.33"
}

# m7i-flex.large (2 vCPU / 8 GB): the Free-Tier-eligible drop-in for
# m6i.large. New AWS accounts start on the Free plan, which refuses to launch
# non-eligible types — with m6i.large the node group dies after an ASG launch
# failure ~30 minutes in, on exactly the first-run path.
variable "instance_type" {
  type    = string
  default = "m7i-flex.large"
}

variable "min_nodes" {
  type    = number
  default = 1
}

variable "max_nodes" {
  type    = number
  default = 4
}

variable "desired_nodes" {
  type    = number
  default = 3
}

variable "spot" {
  type    = bool
  default = false
}

provider "aws" {
  region  = var.region
  profile = var.profile != "" ? var.profile : null

  default_tags {
    tags = {
      "openframe:cluster"   = var.cluster_name
      "openframe:managedBy" = "openframe-cli"
    }
  }
}

data "aws_availability_zones" "available" {
  state = "available"
}

locals {
  azs = slice(data.aws_availability_zones.available.names, 0, 2)
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "6.6.1"

  name = "${var.cluster_name}-vpc"
  cidr = "10.0.0.0/16"

  azs             = local.azs
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]

  enable_nat_gateway = true
  single_nat_gateway = true

  public_subnet_tags = {
    "kubernetes.io/role/elb" = "1"
  }
  private_subnet_tags = {
    "kubernetes.io/role/internal-elb" = "1"
  }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "21.24.1"

  name               = var.cluster_name
  kubernetes_version = var.kubernetes_version

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  # The CLI reaches the API server from the operator's machine.
  endpoint_public_access = true

  # The identity running terraform must be able to use the cluster afterwards
  # (kubeconfig auth goes through `aws eks get-token` with the same identity).
  enable_cluster_creator_admin_permissions = true

  eks_managed_node_groups = {
    default = {
      instance_types = [var.instance_type]
      min_size       = var.min_nodes
      max_size       = var.max_nodes
      desired_size   = var.desired_nodes
      capacity_type  = var.spot ? "SPOT" : "ON_DEMAND"

      # The EBS CSI controller below runs on these nodes and authenticates
      # through the node instance role — no IRSA/OIDC wiring to manage.
      iam_role_additional_policies = {
        ebs_csi = "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
      }

      # The CSI controller reaches that role via IMDS, and it is NOT on host
      # network — one extra network hop. The module's v21 default hop limit of
      # 1 cuts it off ("no EC2 IMDS role found", controller crash-loops, no
      # volume ever binds); 2 restores pod access while keeping IMDSv2 required.
      metadata_options = {
        http_endpoint               = "enabled"
        http_tokens                 = "required"
        http_put_response_hop_limit = 2
      }
    }
  }

  # EKS module v21 sets bootstrap_self_managed_addons = false: EKS itself
  # installs NOTHING, so every addon a working cluster needs must be declared
  # here. Without vpc-cni no pod ever gets a network and the nodes never
  # become Ready; before_compute installs it ahead of the node group so nodes
  # come up working instead of waiting on a broken CNI.
  addons = {
    vpc-cni = {
      most_recent    = true
      before_compute = true
    }
    kube-proxy = {
      most_recent = true
    }
    coredns = {
      most_recent = true
    }

    # Since Kubernetes 1.23 the in-tree EBS provisioner is gone: without this
    # addon every PersistentVolumeClaim stays Pending forever, so the OpenFrame
    # platform (Kafka, MongoDB, Cassandra, …) could never come up.
    aws-ebs-csi-driver = {
      most_recent = true
      configuration_values = jsonencode({
        # Since EKS 1.30 AWS no longer marks the legacy gp2 class as default:
        # a PVC with no explicit storageClassName stays Pending forever. The
        # addon can create a default gp3 class itself (addon >= 1.31.0).
        defaultStorageClass = {
          enabled = true
        }
        controller = {
          # Tag CSI-provisioned volumes with the cluster name: they are created
          # OUTSIDE terraform state, and this tag is the only handle the CLI's
          # post-destroy orphan sweep has on them (see teardown.go).
          extraVolumeTags = {
            "openframe:cluster" = var.cluster_name
          }
        }
      })
    }
  }
}

output "cluster_name" {
  value = module.eks.cluster_name
}

output "cluster_endpoint" {
  value = module.eks.cluster_endpoint
}

output "cluster_certificate_authority_data" {
  value = module.eks.cluster_certificate_authority_data
}

output "region" {
  value = var.region
}
