graph TB
    CLI[CLI Layer] --> Bootstrap[Bootstrap Service]
    CLI --> Cluster[Cluster Commands]
    CLI --> Chart[Chart Commands]
    CLI --> Dev[Dev Commands]
    
    Bootstrap --> ClusterSvc[Cluster Service]
    Bootstrap --> ChartSvc[Chart Service]
    
    Cluster --> ClusterSvc
    Chart --> ChartSvc
    Dev --> DevSvc[Dev Service]
    
    ClusterSvc --> K3D[K3D Provider]
    ClusterSvc --> Prerequisites[Prerequisites Checker]
    
    ChartSvc --> Helm[Helm Manager]
    ChartSvc --> ArgoCD[ArgoCD Provider]
    ChartSvc --> Git[Git Repository]
    
    DevSvc --> Telepresence[Telepresence Provider]
    DevSvc --> Skaffold[Skaffold Provider]
    DevSvc --> Kubectl[Kubectl Provider]
    
    K3D --> Docker[Docker/K3D]
    Helm --> K8s[Kubernetes Cluster]
    Telepresence --> K8s
    Kubectl --> K8s
