# Root module generated by the OpenFrame CLI (do not edit by hand — the CLI
# owns this workspace). Provisions a self-contained GKE cluster: required
# project APIs, a dedicated VPC with pod/service secondary ranges, and a
# regional GKE cluster with one autoscaling node pool. All inputs come from
# terraform.tfvars.json next to this file.

terraform {
  required_version = ">= 1.15.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 7.17.0, < 8"
    }
  }
}

variable "cluster_name" { type = string }
variable "project" { type = string }
variable "region" { type = string }

# Kubernetes <major>.<minor> (e.g. "1.33"); empty means the GKE default.
variable "kubernetes_version" {
  type    = string
  default = ""
}

variable "instance_type" {
  type    = string
  default = "e2-standard-4"
}

variable "min_nodes" {
  type    = number
  default = 1
}

variable "max_nodes" {
  type    = number
  default = 4
}

variable "desired_nodes" {
  type    = number
  default = 3
}

variable "spot" {
  type    = bool
  default = false
}

provider "google" {
  project = var.project
  region  = var.region

  default_labels = {
    openframe-cluster    = var.cluster_name
    openframe-managed-by = "openframe-cli"
  }
}

# GKE needs these services active in the project; disable_on_destroy=false so
# a cluster teardown never switches off APIs other workloads may use.
resource "google_project_service" "required" {
  for_each = toset(["compute.googleapis.com", "container.googleapis.com"])

  service            = each.value
  disable_on_destroy = false
}

module "network" {
  source  = "terraform-google-modules/network/google"
  version = "~> 18.0"

  project_id   = var.project
  network_name = "${var.cluster_name}-vpc"

  subnets = [
    {
      subnet_name   = "${var.cluster_name}-subnet"
      subnet_ip     = "10.0.0.0/20"
      subnet_region = var.region
    }
  ]

  secondary_ranges = {
    "${var.cluster_name}-subnet" = [
      {
        range_name    = "pods"
        ip_cidr_range = "10.4.0.0/14"
      },
      {
        range_name    = "services"
        ip_cidr_range = "10.8.0.0/20"
      }
    ]
  }

  depends_on = [google_project_service.required]
}

# Private nodes have no external IPs (required by orgs enforcing the
# constraints/compute.vmExternalIpAccess policy — a public-node pool lands in
# ERROR state there), so egress (image pulls etc.) goes through Cloud NAT.
resource "google_compute_router" "nat" {
  name    = "${var.cluster_name}-router"
  project = var.project
  region  = var.region
  network = module.network.network_name
}

resource "google_compute_router_nat" "nat" {
  name    = "${var.cluster_name}-nat"
  project = var.project
  region  = var.region
  router  = google_compute_router.nat.name

  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
}

module "gke" {
  # The private-cluster submodule: same interface as the root module plus the
  # private-nodes controls the root module does not expose.
  source  = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"
  version = "~> 44.0"

  project_id = var.project
  name       = var.cluster_name
  region     = var.region
  regional   = true

  network           = module.network.network_name
  subnetwork        = "${var.cluster_name}-subnet"
  ip_range_pods     = "pods"
  ip_range_services = "services"

  kubernetes_version = var.kubernetes_version != "" ? var.kubernetes_version : "latest"

  # Nodes are private (no external IPs — org-policy friendly; egress via the
  # Cloud NAT above). The API endpoint stays public so the operator's machine
  # reaches the cluster without a VPN or Connect Gateway.
  enable_private_nodes    = true
  enable_private_endpoint = false
  master_ipv4_cidr_block  = "172.16.0.0/28"

  # The CLI owns this cluster's lifecycle; deletion protection would break
  # 'openframe cluster delete'.
  deletion_protection = false

  remove_default_node_pool = true

  node_pools = [
    {
      name               = "default"
      machine_type       = var.instance_type
      min_count          = var.min_nodes
      max_count          = var.max_nodes
      initial_node_count = var.desired_nodes
      spot               = var.spot
      disk_size_gb       = 100
    }
  ]
}

output "cluster_name" {
  value = module.gke.name
}

# Bare host — the provider prefixes https:// when building kubeconfigs.
output "cluster_endpoint" {
  value     = module.gke.endpoint
  sensitive = true
}

output "cluster_certificate_authority_data" {
  value     = module.gke.ca_certificate
  sensitive = true
}

output "region" {
  value = var.region
}
